void quicksort_num(int number[], int first, int last);
void quicksort_string(char number[][101], int first, int last);
void mergeSort_num(int arr[], int l, int r);
void merge_num(int arr[], int l, int m, int r);
void mergeSort_string(char arr[][101], int l, int r);
void merge_string(char arr[][101], int l, int m, int r);
void heapify_num(int arr[], int n, int i);
void heapSort_num(int arr[], int n);
void heapify_string(char arr[][101], int n, int i);
void heapSort_string(char arr[][101], int n);
